In [ ]:
import numpy as np

# Broadcasting (o cómo se extienden las dimensiones de dos arrays en ciertas operaciones)

El broadcasting se aplica en las operaciones: +,-,`*`,/, //, `**` entre un array A y un array B de diferentes dimensiones busca encontrar una dimensión del array que sea o bien:


*   Igual a 1
*   A[item].shape == B[item].shape

Esto va de la derecha a la izquierda. Es decir, de la dimensión última hasta la primera. Cuando encuentra alguno de los dos casos resuelve



Por ejemplo, dados los arrays `a,b,c,d` si:

 * `a.shape` es (5,1)
 * `b.shape` es (1,6)
 * `c.shape` es (6,)
 * `d.shape` es () (o sea, `d` es un escalar

 Entonces **a, b, c, d son todos broadcasteables a la shape (5,6)**

In [ ]:
a = np.array([1,2,3,4,5]).reshape(5,1)
b = np.array([1,2,3,4,5,6]).reshape(1,6)
c = np.array([10,20,30,40,50,60])
d = np.array(5)

In [ ]:
arrs = [a,b,c,d]

for i,n in zip(arrs,["a","b","c","d"]):
  print(f"{n}:")
  print(i)
  print(f"shape de {n} => ",i.shape, "\n")

a:
[[1]
 [2]
 [3]
 [4]
 [5]]
shape de a =>  (5, 1) 

b:
[[1 2 3 4 5 6]]
shape de b =>  (1, 6) 

c:
[10 20 30 40 50 60]
shape de c =>  (6,) 

d:
5
shape de d =>  () 



`a` actúa como un array de shape (5,6) donde a[:,0] se broadcastea (extiende) a otras columnas

In [ ]:
a+b

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a*b

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30]])

`b` actúa como un array de shape (5,6) donde  b[0,:] se broadcastea (extiende) a otras filas:


In [ ]:
b*c

array([[ 10,  40,  90, 160, 250, 360]])

In [ ]:
c+b

array([[11, 22, 33, 44, 55, 66]])

`c` actúa como un array de shape (1,6) y por extensión de (5,6) donde c[:] se replica en cada fila

In [ ]:
a*c

array([[ 10,  20,  30,  40,  50,  60],
       [ 20,  40,  60,  80, 100, 120],
       [ 30,  60,  90, 120, 150, 180],
       [ 40,  80, 120, 160, 200, 240],
       [ 50, 100, 150, 200, 250, 300]])

d actúa como un array de (5,6) donde valor se repite para cada posición

In [ ]:
a*d

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [ ]:
b+d

array([[ 6,  7,  8,  9, 10, 11]])

**Sin embargo, esto no funciona para la multiplicación matricial `@`**. Donde si no se cumple la regla de:

A(nxm) @ B(nxm) => a[m] == b[n]

La operación va a tirar error

a@b se puede porque a (5,1) y b (1,6) y produce una matriz 5x6

In [14]:
a@b

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30]])

Pero b@a no se puede

In [ ]:
b@a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 6)

Sin embargo, `a*b` y `b*a` sí se broadcastean y son iguales

In [ ]:
a*b == b*a

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])